name: Build Examples

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths:
      - Makefile
      - alternate/**
      - examples/**
      - internals/**
      - ndr/**
      - src/**
      - utils/**
      - win/**
      - .github/workflows/build-examples.yml

jobs:
  build-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Install V
        uses: vlang/setup-v@v1.4

      - name: Install mingw
        run: |
          sudo apt install -y gcc-mingw-w64

      - name: ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Build Examples
        run: |
          mkdir -p ~/.vmodules/qtc_de
          ln -s $(pwd) ~/.vmodules/qtc_de/rpv
          make all

      - name: Archive example executables
        uses: actions/upload-artifact@v4
        with:
          name: rpv-compiled-examples
          path: examples/*.exe
