name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - alternate/**
      - internals/**
      - ndr/**
      - src/**
      - utils/**
      - win/**
      - .github/workflows/build-docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install V
        uses: vlang/setup-v@v1.4

      - name: Build Docs
        run: |
          mkdir html modules
          mv internals ndr src utils win modules/
          v doc -all -f html -o html -m modules/ .
          echo '<meta http-equiv="refresh" content="0;url=https://qtc-de.github.io/rpv/rpv.html" />' > html/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html/'

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
